# Generated by Django 2.1.3 on 2018-11-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='core.Article'),
        ),
        migrations.AddField(
            model_name='entity',
            name='domain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='entities',
            field=models.ManyToManyField(to='core.Article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(to='core.Article'),
        ),
    ]
