# Generated by Django 2.1.3 on 2018-11-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('offset', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Entity')),
            ],
        ),
    ]
